services:
  db:
    image: postgres:16
    container_name: Fitzo_db
    environment:
      POSTGRES_USER: fitzouser
      POSTGRES_PASSWORD: fitzopassword
      POSTGRES_DB: fitzo_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fitzo-network
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: fitzo_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@fitzo.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - fitzo-network
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: fitzo_azurite
    command: "azurite --blobHost 0.0.0.0 --queueHost 0.0.0.0 --tableHost 0.0.0.0"
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    volumes:
      - azurite_data:/data
    networks:
      - fitzo-network

volumes:
  postgres_data:
  azurite_data:

networks:
  fitzo-network:
    driver: bridge

