name: Fitzo CI-CD pipeline-backend

on:
  push:
    branches: ["main"]
    paths:
      - 'src/Fitzo.API/**'
      - 'src/Fitzo.Functions/**'
      - 'src/Fitzo.Shared/**'
      - 'tests/**'
      - '.github/workflows/backend_pipeline.yml' 
  pull_request:
    branches: [ "main" ]
    paths:
      - 'src/Fitzo.API/**'
      - 'src/Fitzo.Functions/**'
      - 'src/Fitzo.Shared/**'
      - 'tests/**'

env:
  SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  build-and-test:
    name: Build, test, sonar
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
          POSTGRES_DB: fitzo_test_db
        ports:
          - 5432:5432 
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install SonarScanner
        run: dotnet tool install --global dotnet-sonarscanner 

      - name: SonarCloud start
        run: |
          dotnet sonarscanner begin /k:"Fitzo-Team_Fitzo" /o:"fitzo-team" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.opencover.reportsPaths="**/coverage.opencover.xml"

      - name: Restore Dependencies
        run: dotnet restore Fitzo.Backend.sln

      - name: Build
        run: dotnet build Fitzo.Backend.sln --no-restore --configuration Release 

      - name: Test and Coverage
        run: dotnet test Fitzo.Backend.sln --no-build --configuration Release --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
        env: 
          ConnectionStrings__DefaultConnection: "Host=localhost;Port=5432;Database=fitzo_test_db;Username=testuser;Password=testpassword"

      - name: End Sonar
        run: dotnet sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"

  security-scan:
    name: Trivy scan
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Image Name env
        run: |
          RAW_NAME=ghcr.io/${{ github.repository }}/fitzo-api
          LOWER_NAME=$(echo $RAW_NAME | tr '[:upper:]' '[:lower:]')
          echo "IMAGE_NAME=$LOWER_NAME" >> $GITHUB_ENV

      - name: Build Docker Image
        run: | 
          docker build -f src/Fitzo.API/Dockerfile -t ${{ env.IMAGE_NAME }}:${{ github.sha }} .

      - name: Run Trivy
        uses: aquasecurity/trivy-action@master
        with: 
          image-ref: '${{ env.IMAGE_NAME }}:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'

      - name: Push image to GHCR
        run: |
          docker push ${{ env.IMAGE_NAME }}:${{ github.sha }}
          docker tag ${{ env.IMAGE_NAME }}:${{ github.sha }} ${{ env.IMAGE_NAME }}:latest
          docker push ${{ env.IMAGE_NAME }}:latest

  deploy-api:
    name: Deploy API
    needs: security-scan
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps: 
      - name: Image name
        run: |
          RAW_NAME=ghcr.io/${{ github.repository }}/fitzo-api
          LOWER_NAME=$(echo $RAW_NAME | tr '[:upper:]' '[:lower:]')
          echo "IMAGE_NAME=$LOWER_NAME" >> $GITHUB_ENV

      - name: Deploy to WebApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'fitzo'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: '${{ env.IMAGE_NAME }}:${{ github.sha }}'

  deploy-functions:
    name:  Deploy Functions
    needs: build-and-test 
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
        
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
            dotnet-version: 8.0.x

      - name: Publish Functions
        run: dotnet publish src/Fitzo.Functions/Fitzo.Functions.csproj -c Release -o ./func-publish

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
            app-name: 'fitzofunc'
            package: './func-publish'
            publish-profile: ${{ secrets.AZURE_FUNC_PUBLISH_PROFILE }}